### ISSUE TITLE
The Studio gallery treatment

### ISSUE THREAD

**Issue by micahmicah** [risd/risd-graduate-welcome#11]
We need a treatment for the studio section. I'm considering using the `Layout` widget to make this a little more clear and allow us to have a "gallery" style page.

First I'm going to leverage the existing `narrative_sections` structure to build it, if it's too confusing I'll consider either adding a `gallery` widget or another repeatable for that clearly calls out that it's a gallery.

**Comment by mmarol** [comment]
`Packery` has been implemented.

**Comment by micahmicah** [comment]
After looking at several options we've decided to go away from the scalable interaction shown [on packery's site](http://packery.metafizzy.co/events.html) and to opt for a lightbox style interaction like we did on the [nature lab's site](http://naturelab.risd.edu/collections/edna-w-lawrence-natural-history-collection/).
