### ISSUE TITLE
BEYOND RISD lightbox images 

### ISSUE THREAD

**Issue by micahmicah** [risd/risd-graduate-welcome#12]
Is it possible to lightbox the images in the [BEYOND RISD](http://welcomegrad.risd.edu/beyond-risd) section?

I realize this has some behavior implications in terms of expanding and collapsing each profile.

![screen shot 2017-02-03 at 9 47 20 am](https://cloud.githubusercontent.com/assets/1166088/22595508/c3289aa2-e9f5-11e6-9dd4-9c62ffec51b4.png)

![screen shot 2017-02-03 at 9 47 59 am](https://cloud.githubusercontent.com/assets/1166088/22595536/db71fc02-e9f5-11e6-95f7-c689137045ab.png)

**Comment by mmarol** [comment]
We can, but the behavior implications are real, and it doesn't necessarily feel like a useful interaction. 

A possibility could be to make the image full column width?

**Comment by micahmicah** [comment]
I worry that to go from a small image to a full width image on a single click is too much shifting around, where as a two step process of opening the profile and then expanding the image gives the more curious user an opportunity to get a better view of the image.
