### ISSUE TITLE
Footer Breadcrumbs

### ISSUE THREAD

**Issue by micahmicah** [risd/risd-graduate-welcome#15]
Currently the breadcrumbs for the footer work _most_ of the time, in terms of `sections`.
![screen shot 2017-02-03 at 2 41 45 pm](https://cloud.githubusercontent.com/assets/1166088/22605669/e5efeef4-ea1e-11e6-9793-a26ac023a542.png)

And `pages` within `sections`

![screen shot 2017-02-03 at 2 42 01 pm](https://cloud.githubusercontent.com/assets/1166088/22605677/f06a88a8-ea1e-11e6-9168-758ddbd271bd.png)

However once we make it down to  `stories`, that are within `pages` that are within `sections` the trail goes dead.

![screen shot 2017-02-03 at 2 43 02 pm](https://cloud.githubusercontent.com/assets/1166088/22605703/14641238-ea1f-11e6-9106-4ca5f7e3a4ac.png)

I wasn't able to determine how to "swim up stream" from story, to page, to section using the relationship module.

**Comment by mmarol** [comment]
This has been updated to with some sorta weird, but fairly appropriate logic.

If a `Story` has multiple pages related to it, the breadcrumb will be `Home / Stories / Story`.

If is has a single related page, it will follow the Section to Page to Story breadcrumb path.
