### ISSUE TITLE
javascript build process

### ISSUE THREAD

**Issue by micahmicah** [risd/risd-graduate-welcome#2]
I'm a bit unclear on how javascript is being dealt with in this repo in contrast to the "out of the box" handling of javascript that comes with webhook. I did some potentially dumb stuff in jerry rigging jQuery and `main.js` in this commit https://github.com/risd/risd-graduate-welcome/commit/05b0d26ef261662ba8e42931693258fa3c9baafe.

**Comment by rubillionaire** [comment]
The [gruntfile](https://github.com/risd/risd-graduate-welcome/blob/develop/Gruntfile.js#L20) is pointing towards [`script/src/index.js`](https://github.com/risd/risd-graduate-welcome/blob/develop/script/src/index.js) being your entry point.

This is a pattern I discussed with Jay as being our default. All sites should be the same. But it doesn't look like that aspect has been baked into our `webhook-generator` repo. Unless it was implemented as a theme?
