### ISSUE TITLE
H3 styling on Summer Programs page

### ISSUE THREAD

**Issue by room421** [risd/risd-graduate-welcome#24]
On http://welcomegrad.risd.edu/next-steps/summer-programs/, could the H3's within each expandable section have a differentiating style (preferably smaller) than the h3 with the drawer class. When the expandable is open, the hierarchy gets confused:
![screen shot 2017-02-07 at 3 50 11 pm](https://cloud.githubusercontent.com/assets/4335334/22710926/37f93eb8-ed4d-11e6-84d3-a322671cdf41.png)

**Comment by room421** [comment]
I could also just make these all H4's if that works...

fyi, I deleted Intar's MDES and MA while the content gets worked on so these expandables don't go live. Still a lot of content holes with these 2. TLAD still to come as well.

**Comment by micahmicah** [comment]
Let's keep them as H3s, I can adjust. I had bumped up the text like that so it was more easily scannable but I think i felt it needed that because I was opening and closing all the drawers, for a user that only looks at information relevant to them we can have the h3s be smaller.

**Comment by room421** [comment]
@micahmicah  Just tried h4's. It looks fine. http://welcomegrad.risd.edu/next-steps/summer-programs/

If you agree, you can close this.
