### ISSUE TITLE
filterable contact list

### ISSUE THREAD

**Issue by micahmicah** [risd/risd-graduate-welcome#3]
I'm looking to build a custom dropdown that can filter out different contact information for Graduate Program directors.

I'd like to hide all the program directors information until it is selected from a dropdown and at that point it would display a content block that has their name, e-mail, department, job title, etc.

My assumption is that I'd load everything into the DOM and hide/show it using Javascript. 

@mmarol is there a CodePen you know of that I should look at? 

I know there's little that can be done to style browser dropdown menus so I assume this functionality would need to be mimicked in Javascript, is there a "plugin" or library that we can lean on to do this? Any advice about how to proceed would be great.

Thanks!

**Comment by mmarol** [comment]
@micahmicah pull and take a look. If it looks good, the issue can be closed.
