### ISSUE TITLE
apple touch icons in template code

### ISSUE THREAD

**Issue by room421** [risd/risd-graduate-welcome#32]
There's a whole bunch of png icons referenced in the template code. These are overwhelming the siteimprove report because they show up as broken links on every page. Do we need them?

<img width="867" alt="screen shot 2017-02-10 at 5 53 14 pm" src="https://cloud.githubusercontent.com/assets/4335334/22848096/e57e9320-efbf-11e6-80e5-139d2273eb8e.png">

**Comment by room421** [comment]
Hi Jay -- do you know what these are? I'm trying to evaluate legit errors on the grad welcome site in Siteimprove and these "broken" links are bloating the report.

**Comment by mmarol** [comment]
I will take a look. I think I would just need to specify absolute paths instead of relative ones.

**Comment by room421** [comment]
This can happen after this week's undergrad push. Just wanted to get it on your radar.

**Comment by mmarol** [comment]
I just pushed a fix. Let me know if you still get errors.
