### ISSUE TITLE
reconfigure titles etc for Get In Touch module

### ISSUE THREAD

**Issue by laurenmaas** [risd/risd-graduate-welcome#37]
Need to work through the hidden vs. visible content types under contacts.

Under contact names we **don't** need to see:
department

We **do** need to see:
faculty rank (Assistant Professor, etc)
department role (graduate program director, department head)
...in some cases they are **both** gpd and department head

the other outlier here is department assistant who don't have a faculty rank (so it would just be department assistant and contact email under their names)

![screen shot 2018-01-18 at 2 32 52 pm](https://user-images.githubusercontent.com/28458646/35118893-3aa8d17a-fc8b-11e7-80bc-95ba322996d8.png)

**Comment by cmiller02** [comment]
Hey Lauren - all seem like good points. This is the page on the live site that your above webhook page would affect, right? Also, while I'm in here I'll go ahead and assign this issue to Jay. Thanks for entering this!

![screen shot 2018-01-18 at 4 05 51 pm](https://user-images.githubusercontent.com/14020234/35121572-ded23e16-fc69-11e7-9f7c-be416044f44d.png)

**Comment by laurenmaas** [comment]
It would be all of the departmental entries for the Get in touch module.

L

Lauren Maas
Copywriter
RISD MEDIA GROUP
Rhode Island School of Design

work: 401.709.8638
cell: 732.762.0084

**Comment by mmarol** [comment]
I've added 3 new fields, **Faculty rank**, **Primary role** and **Secondary role** to at least temporarily solve this issue. The **Title** field will no longer be used.

@laurenmaas if you think the current contents of the **Title** field fit into any of the new fields, I can probably move that content over real quick.

The changes can be seen at https://risd-graduate-welcome.risd.systems/. Once they are approved there, I will push them to the live site.
