### ISSUE TITLE
Broken Breadcrumb Links

### ISSUE THREAD

**Issue by cmiller02** [risd/risd-graduate-welcome#40]
@teddybradford - we have 12 breadcrumb links on http://welcomegrad.risd.edu/ that are broken and I believe they can only be fixed at the template level, as I checked the CMS: https://risd-graduate-welcome.risd.systems/cms and don't see where I can edit them.

Here is a spreadsheet that tells you what the broken links are, what pages they are located on, includes small screenshots of where they are on the page, and what urls the links should be fixed with. Can you please fix these? Thanks!

[welcome_grad_broken_links_2_8_18.xlsx](https://github.com/risd/risd-graduate-welcome/files/1711547/welcome_grad_broken_links_2_8_18.xlsx)

**Comment by room421** [comment]
Community link still is incorrect at http://welcomegrad.risd.edu/learning-environment/community/vernacular-spectacular/
![screen shot 2018-02-09 at 4 15 43 pm](https://user-images.githubusercontent.com/4335334/36050427-8426211a-0db4-11e8-9ec8-46684e2f410d.png)

**Comment by teddybradford** [comment]
@room421 I think you may have looked prior to the new change propagating to the live site. It seems to be working fine for me. Can you confirm that it's working for you now?

**Comment by room421** [comment]
You're right. Totally good now. Thanks!

**Comment by room421** [comment]
oh, wait. One last one. 
http://welcomegrad.risd.edu/community/supporting-your-research/the-gravedigger/
![screen shot 2018-02-09 at 6 00 28 pm](https://user-images.githubusercontent.com/4335334/36054263-693408ea-0dc3-11e8-9347-01273b0d001a.png)
Home link is wrong.

**Comment by teddybradford** [comment]
Squashed it!
