### ISSUE TITLE
risd-graduate-welcome.risd.systems AuthenticationRequired error

### ISSUE THREAD

**Issue by teddybradford** [risd/risd-graduate-welcome#41]
http://risd-graduate-welcome.risd.systems is showing the following error:

```
<Error>
  <Code>AuthenticationRequired</Code>
  <Message>Authentication required.</Message>
</Error>
```

Any ideas, @rubillionaire?

**Comment by room421** [comment]
@teddybradford @rubillionaire this one seems resolved somehow?

**Comment by rubillionaire** [comment]
@teddybradford @room421 This appears to have cleared up? Looking good to me at the moment.

**Comment by teddybradford** [comment]
Looks like it. Not sure why that happened. 🤷‍♂️
I'll close this.
