### ISSUE TITLE
Add font files

### ISSUE THREAD

**Issue by mmarol** [risd/risd-graduate-welcome#6]

**Comment by mmarol** [comment]
@rubillionaire I've uploaded the font files and deployed it. When I got to something like http://welcomegrad.risd.edu/static/fonts/541402/1C72577AB7AD828D6.css, the file exists.

When I go through the steps typography.com outlines, the last step involves them confirming the installation of the fonts, but I get this error:

![screen shot 2017-02-01 at 09 57 56](https://cloud.githubusercontent.com/assets/6997772/22511872/107f3a78-e865-11e6-85b2-3abfb175751f.png)

Not too sure why this is happening.

**Comment by rubillionaire** [comment]
This could be because welcomegrad.risd.edu is only available on the on
campus network. OIT needs to make the CNAME record public, so that you can
visit the site from outside of RISD. I noticed this when I tried visiting
last night from home.

**Comment by mmarol** [comment]
@room421 is this a thing I can get in contact with them about, or will you be doing that?
