### ISSUE TITLE
Bullet list size

### ISSUE THREAD

**Issue by mmarol** [risd/risd-graduate-welcome#9]
http://welcomegrad.risd.edu/next-steps/financing2/

The bulleted list type size is small and the font is incorrect I think.

**Comment by micahmicah** [comment]
I had originally done this intentionally to help further separate and adjust the typographic texture of the page, but I think it's safe to say that it's more confusing than helpful :)

**Comment by room421** [comment]
The example URL has changed to http://welcomegrad.risd.edu/next-steps/financing-your-education/

Could they bump up a point or two and still maintain some separation?
